main = "./src/index.ts"
compatibility_date = "2022-11-11"
workers_dev = true
# logpush = true
# node_compat = true
minify = true


[env.dev]
name = "note-reward-manager-dev"

[env.dev.vars]
NETWORK = "mainnet"

[env.beta]
name = "note-reward-manager-beta"

[env.prod]
name = "note-reward-manager"

# [triggers]
# crons = ["0/10 * * * *"]
