main = "./src/index.ts"
compatibility_date = "2022-11-11"

workers_dev = true
node_compat = true
minify = true
usage_model = "bundled"

[env.dev]
name = "liquidation-bot-dev"

[env.dev.vars]
ACCOUNT_SERVICE_URL = "https://accounts-dev.notional-finance.workers.dev/"

[env.beta]
name = "liquidation-bot-beta"

[env.prod]
name = "liquidation-bot"
