main = "./src/index.ts"
compatibility_date = "2022-11-11"

workers_dev = true
node_compat = true
minify = true
usage_model = "bundled"

[env.dev]
name = "vault-liquidator-dev"

[env.dev.vars]
NETWORK = 'ArbitrumOne'
FLASH_LIQUIDATOR_CONTRACT = '0xd754329B32e3221C4Abe05b7C1a56989CA7578E3'
FLASH_LIQUIDATOR_OWNER = '0xE6FB62c2218fd9e3c948f0549A2959B509a293C8'
FLASH_LENDER_ADDRESS = '0x794a61358D6845594F94dc1DB02A252b5b4814aD'
FLASH_LOAN_BUFFER = '1005'
NOTIONAL_PROXY_CONTRACT = '0x1344A36A1B56144C3Bc62E7757377D288fDE0369'
GAS_COST_BUFFER = '1000'
DUST_THRESHOLD = '0'
PROFIT_THRESHOLD = '0'

[env.beta]
name = "vault-liquidator-beta"

[env.prod]
name = "vault-liquidator"
