main = "./src/index.ts"
compatibility_date = "2022-11-11"

workers_dev = true
node_compat = true
minify = true
usage_model = "bundled"

[env.dev]
name = "exchange-rate-monitor-dev"

[env.beta]
name = "exchange-rate-monitor-beta"

[env.prod]
name = "exchange-rate-monitor"
