account_id = '274f86c6dcfbb77c09e49e86d101c753'
main = "./src/index.ts"
compatibility_date = "2022-11-11"

workers_dev = true
node_compat = true
minify = true
logpush = true


[env.dev]
name = "rewards-dev"
kv_namespaces = [
  { binding = "REWARDS_KV", id = "5d1577f627494c08ad97338960a5a4a8" }
]

[env.dev.vars]
NETWORK = 'ArbitrumOne'
TREASURY_MANAGER_ADDRESS = '0x53144559c0d4a3304e2dd9dafbd685247429216d'
MANAGER_BOT_ADDRESS = '0xa28a0bA9633342793218D9bd8d92CBC52231361C'
REINVEST_TIME_WINDOW_IN_HOURS=24

[env.beta]
name = "rewards-beta"

[env.prod]
name = "rewards"

[triggers]
# Run two times every other hour, once to claim tokens and then again to reinvest
# reinvestment and claim will only happen once in specified REINVEST_TIME_WINDOW_IN_HOURS
# it is tightly coupled to how we are triggering claiming and reinvestment
crons = ["0 */2 * * *", "10 */2 * * *"]
