name = "system-cache-dev"
main = "./src/index.ts"
compatibility_date = "2022-07-07"
account_id = "274f86c6dcfbb77c09e49e86d101c753"

workers_dev = true
node_compat = true
minify = true

[vars]
DD_BASE_URL = "https://datadoghq.com"
VERSION = "v2"

[durable_objects]
bindings = [
  { name = "SYSTEM_CACHE", class_name = "SystemCache", script_name = "system-cache-dev" }
]

r2_buckets = [
  { binding = "VAULT_RETURNS", bucket_name = "vault-returns-dev", preview_bucket_name = "vault-returns-dev" }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["SystemCache"]

[triggers]
crons = [
    "*/10 * * * *",
    "0 0 * * *"
]

[env.beta]
name = "system-cache-beta"

[env.beta.vars]
DD_BASE_URL = "https://datadoghq.com"
VERSION = "v2"

[env.beta.durable_objects]
bindings = [
  { name = "SYSTEM_CACHE", class_name = "SystemCache", script_name = "system-cache-beta" }
]

[[env.beta.r2_buckets]]
binding = "VAULT_RETURNS"
bucket_name = "vault-returns-beta"

[[env.beta.migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["SystemCache"]
