name = "system-cache-dev"
main = "./src/index.ts"
compatibility_date = "2022-07-07"

workers_dev = true
node_compat = true
minify = true

[durable_objects]
bindings = [{name = "SYSTEM_CACHE", class_name = "SystemCache"}]

[[r2_buckets]]
binding = 'VAULT_RETURNS'
bucket_name = 'vault-returns'

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["SystemCache"]

[vars]
VERSION = 'v2'

[triggers]
crons = [
    "*/10 * * * *",
    "0 0 * * *"
]

[env.dev]

[env.beta]
name = "system-cache-beta"

[env.prod]
name = "system-cache"