name = "metrics-dev"
main = "./src/index.ts"
compatibility_date = "2022-07-07"

workers_dev = true
node_compat = true
minify = true
usage_model = "bundled"

[env.dev]
name = "metrics-dev"
[env.staging]
name = "metrics-staging"
[env.production]
name = "metrics"
