main = "./src/index.ts"
compatibility_date = "2022-11-11"

workers_dev = true
node_compat = true
minify = true
usage_model = "bundled"

[env.local]
durable_objects.bindings = [
  { name = "ACCOUNT_CACHE", class_name = "AccountCache" },
]

[env.dev]
name = "accounts-dev"
bindings = [
  { name = "ACCOUNT_CACHE", class_name = "AccountCache", script_name = "accounts-dev" }
]

[env.beta]
name = "accounts-beta"

[env.prod]
name = "accounts"
