name: ci
environment: dev
on:
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.8
    env:
      NX_BLOCK_NATIVE_DAPP_ID: ${{ secrets.NX_BLOCK_NATIVE_DAPP_ID }}
      NX_CONTACT_EMAIL: ${{ secrets.NX_CONTACT_EMAIL }}
      NX_DD_APP_ID: ${{ secrets.NX_DD_APP_ID }}
      NX_DD_CLIENT_TOKEN: ${{ secrets.NX_DD_CLIENT_TOKEN }}
      NX_DD_SITE: ${{ secrets.NX_DD_SITE }}
      NX_GOOGLE_ANALYTICS_ID: ${{ secrets.NX_GOOGLE_ANALYTICS_ID }}
      NX_INFURA_KEY: ${{ secrets.NX_INFURA_KEY }}
      NX_APP_URL: ${{ secrets.NX_APP_URL }}
      NX_SYSTEM_CACHE_URL: ${{ secrets.NX_SYSTEM_CACHE_URL }}
      NX_ALCHEMY_KEY: ${{ secrets.NX_ALCHEMY_KEY }}
      NX_EXCHANGE_RATE_API: ${{ secrets.NX_EXCHANGE_RATE_API }}
    with:
      number-of-agents: 3
      init-commands: |
        yarn nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        yarn nx-cloud record -- yarn nx workspace-lint
      parallel-commands-on-agents: |
        yarn nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.8
    with:
      number-of-agents: 3
