name: Deploy Cloudflare Worker
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy to: <dev|stage|prod>'
        required: true
        default: 'dev'
      workers:
        description: 'Worker Projects: comma separated list of worker names'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile

      - name: Wrangler Publish
        shell: bash
        run: yarn nx run-many --target=wrangler-publish --config=./wrangler.toml --projects=${{ github.event.inputs.workers }} --env ${{ github.event.inputs.environment }}
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKER_TOKEN }}