name: Deploy Cloudflare Worker
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy to: <dev|beta|prod>'
        required: true
        default: 'dev'
      workers:
        description: 'Worker Projects: comma separated list of worker names'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    name: Deploy Worker
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile

      - name: Wrangler Publish
        shell: bash
        run: yarn nx run-many --target=wrangler-publish --projects=${{ github.event.inputs.workers }} --env ${{ github.event.inputs.environment || 'dev' }}
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKER_TOKEN }}
          NX_ALCHEMY_KEY: ${{ secrets.NX_ALCHEMY_KEY }}
          NX_EXCHANGE_RATE_API: ${{ secrets.NX_EXCHANGE_RATE_API }}
          NX_DD_APP_ID: ${{ secrets.NX_DD_APP_ID }}
          NX_DD_CLIENT_TOKEN: ${{ secrets.NX_DD_CLIENT_TOKEN }}
          NX_DD_SITE: ${{ secrets.NX_DD_SITE }}