on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy to: <staging|production>'
        required: true
        default: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile

      - name: Version
        shell: bash
        run: yarn nx affected --base=last-release --target=wrangler-publish --env ${{ github.event.inputs.environment }}
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}