name: deploy-web
on:
  push:
    branches:
      - main
      - beta
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Yarn Install
        run: yarn install --frozen-lockfile
      - name: Build Web
        run: yarn nx build web --parallel
      - name: Publish Staging
        if: github.ref_name == 'main'
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: notional-web-staging
          directory: dist/apps/web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Beta
        if: github.ref_name == 'beta'
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: notional-web-beta
          directory: dist/apps/web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}