name: deploy-web
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy to: <dev|stage|prod>'
        required: true
        default: 'dev'
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Yarn Install
        run: yarn install --frozen-lockfile
      - name: Build Web - Stage
        if: github.event.inputs.environment == 'stage'
        run: yarn nx build web --parallel
        env:
          NX_BLOCK_NATIVE_DAPP_ID: ${{ secrets.NX_BLOCK_NATIVE_DAPP_ID }}
          NX_CONTACT_EMAIL: ${{ secrets.NX_CONTACT_EMAIL }}
          NX_DD_APP_ID: ${{ secrets.NX_DD_APP_ID }}
          NX_DD_CLIENT_TOKEN: ${{ secrets.NX_DD_CLIENT_TOKEN }}
          NX_DD_SITE: ${{ secrets.NX_DD_SITE }}
          NX_GOOGLE_ANALYTICS_ID: ${{ secrets.NX_GOOGLE_ANALYTICS_ID }}
          NX_INFURA_KEY: ${{ secrets.NX_INFURA_KEY }}
          NX_APP_URL: https://beta.notional.finance
          NX_SYSTEM_CACHE_URL: https://system-cache-stage.notional-finance.workers.dev
      - name: Build Web
        if: github.event.inputs.environment != 'stage'
        run: yarn nx build web --parallel
        env:
          NX_BLOCK_NATIVE_DAPP_ID: ${{ secrets.NX_BLOCK_NATIVE_DAPP_ID }}
          NX_CONTACT_EMAIL: ${{ secrets.NX_CONTACT_EMAIL }}
          NX_DD_APP_ID: ${{ secrets.NX_DD_APP_ID }}
          NX_DD_CLIENT_TOKEN: ${{ secrets.NX_DD_CLIENT_TOKEN }}
          NX_DD_SITE: ${{ secrets.NX_DD_SITE }}
          NX_GOOGLE_ANALYTICS_ID: ${{ secrets.NX_GOOGLE_ANALYTICS_ID }}
          NX_INFURA_KEY: ${{ secrets.NX_INFURA_KEY }}
          NX_APP_URL: https://${{ github.event.inputs.environment || 'dev' }}.notional.finance
          NX_SYSTEM_CACHE_URL: https://system-cache-${{ github.event.inputs.environment || 'dev' }}.notional-finance.workers.dev
      - name: Publish Dev
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: notional-web-${{ github.event.inputs.environment || 'dev' }}
          directory: dist/apps/web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}