name: release

on:
  - workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "gituser@notionalfinance.com"
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
      - run: yarn install --frozen-lockfile
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          last-successful-event: 'release'
      - name: Version
        shell: bash
        run: |
          yarn nx affected --target=build-lib
          yarn nx affected --target=version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}